spring:
  application:
    name: To-Do-List-App
  datasource:
    url: jdbc:sqlite:ToDoListDB.db
    driver-class-name: org.sqlite.JDBC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming: PhysicalNamingStrategyStandardImp
server:
  port: 8081
